version: '3.8'

services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    ports:
      - "8000:8000"
    environment:
      - NUM_NODES=5
      - THRESHOLD=3
      - SCHEDULER_PORT=8000
      - HEARTBEAT_INTERVAL=10
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    networks:
      - crypto_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/statistics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  node_0:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NODE_ID=node_0
      - SCHEDULER_HOST=scheduler
      - SCHEDULER_PORT=8000
      - LOG_LEVEL=INFO
    depends_on:
      - scheduler
    volumes:
      - ./logs:/app/logs
    networks:
      - crypto_network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  node_1:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NODE_ID=node_1
      - SCHEDULER_HOST=scheduler
      - SCHEDULER_PORT=8000
      - LOG_LEVEL=INFO
    depends_on:
      - scheduler
    volumes:
      - ./logs:/app/logs
    networks:
      - crypto_network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  node_2:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NODE_ID=node_2
      - SCHEDULER_HOST=scheduler
      - SCHEDULER_PORT=8000
      - LOG_LEVEL=INFO
    depends_on:
      - scheduler
    volumes:
      - ./logs:/app/logs
    networks:
      - crypto_network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  node_3:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NODE_ID=node_3
      - SCHEDULER_HOST=scheduler
      - SCHEDULER_PORT=8000
      - LOG_LEVEL=INFO
    depends_on:
      - scheduler
    volumes:
      - ./logs:/app/logs
    networks:
      - crypto_network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  node_4:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NODE_ID=node_4
      - SCHEDULER_HOST=scheduler
      - SCHEDULER_PORT=8000
      - LOG_LEVEL=INFO
    depends_on:
      - scheduler
    volumes:
      - ./logs:/app/logs
    networks:
      - crypto_network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

networks:
  crypto_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  logs:
    driver: local